# Generated by Django 2.2.7 on 2020-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20200406_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
