# Generated by Django 2.2.7 on 2020-04-07 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20200407_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
