# Generated by Django 2.2.7 on 2020-04-08 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0005_auto_20200408_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user', 'text')},
        ),
    ]
