# Generated by Django 2.2.7 on 2020-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20200408_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False),
        ),
    ]
