# Generated by Django 2.2.7 on 2020-04-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20200408_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
