# Generated by Django 2.2.7 on 2020-04-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_auto_20200410_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('critical', 'critical'), ('high', 'high'), ('moderate', 'moderate'), ('low', 'low')], max_length=15),
        ),
    ]
