# Generated by Django 2.2.7 on 2020-04-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0013_auto_20200411_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('critical', 'critical'), ('high', 'high'), ('moderate', 'moderate'), ('low', 'low')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
